### ISSUE TITLE
Tagging an upload when used with polymorphic resource

### ISSUE THREAD

**Issue by kevinelliott** [cloudinary/cloudinary_gem#131]
When mapping an upload (such as a Photo resource) to another resource by means of a polymorphic relationship, there is no way to specify the tag(s) because it is used for multiple relationships.

For example, let's say we have a Photo (which has the cloudinary integration via carrierwave) which belongs to User, Place, and Company. The photos will not be tagged with "user", "place" or "company" because the tags are defined in the Photo class, which does not know which resource it is representing.

A potential solution could be introspection into the class instance, detecting the polymorphic relationship, pulling out the tag from the class name, or via a method defined on the polymorphic instance -- but as is now, I don't believe this is supported.

**Comment by tocker** [comment]
Hi @kevinelliott ,

Sorry for the long delay in our response.
I'm assuming from your question that Photo is a model. 

```ruby
class Photo < ActiveRecord::Base
  attr_accessible :content
  belongs_to :photoable, polymorphic: true

end
```
This is not necessary if you're simply attaching a photo to the User, Place and Company models. In that case you can use a `photo` field in those models.
Either way, you can specify tags by overriding the `tags` method in the uploader. The uploader has access to the encapsulating Model via the `model` variable. Cloudinary will use the return value (an `Array`) as the tags for the image ([right here](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/storage.rb#L32-32)).

```ruby
class PhotoUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  # if Photo has it's own model and a "photoable" polymorphic association
  def tags
    model.photoable_type
  end

  # if photo is a field in the User, Place, and Company models
  def tags
    model.class.name
  end
end
```

If you'd rather not override the `tags` method, you can also use CarrierWave's `process` method:

```ruby
class PhotoUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  def association_tag
    { :tags => model.photoable_type }
  end

  process :association_tag
end
```

I'm closing this issue due to the elapsed time since it was open... but please feel free to reopen or create a new one if you have any more issues.
