### ISSUE TITLE
Expires at in sign_url

### ISSUE THREAD

**Issue by ombr** [cloudinary/cloudinary_gem#152]
Is there any way to add a timestamp and expires_at to a sign_url ? (without using private_download_url)

Thanks.

**Comment by taragano** [comment]
`sign_url` is used only for the initial generation of the image. After the image is generated, it can be accessed without any signature at all, also it will be cached in the CDN. In order to make an image available only for a certain time, it'll need to be uploaded as `private` and you'll need to use the `private_download_url` method so the URL will be both expired after the given time, and won't be cached in the CDN.

**Comment by justinlyman** [comment]
What is the default url expiration time when using the private_download_url helper?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
