### ISSUE TITLE
New extended identifier breaks querying by identifier

### ISSUE THREAD

**Issue by adambrod** [cloudinary/cloudinary_gem#153]
When I upgraded to cloudinary gem 1.1 with carrier_wave 0.10.0, it broke some of our code.  To simplify, we have a `Book` model that uses `mount_uploader` to attach to an `Image` which is a subclass of `CarrierWave::Uploader::Base`.

Our test does the following 
1. creates a `Book` and attaches an 'Image' to the book and persists it
2. Runs the query `Book.where(image: @book.image.identifier)` and expects to find the book

```
# This test passes in cloudinary gem 1.0 and breaks in 1.1
@book = FactoryGirl.create(:book)
expect(Book.where(image: @book.image.identifier).count).to eq 1
```

It seems that '@book.image.identifier' returns `"v1405004424/book-title-1-here-by--test.jpg"` but the value in the database is the new extended format: `"image/upload/v1405004424/book-title-1-here-by--test.jpg"`

What is the correct way to query for an uploader? Should it not be queried by identifier? My work around is to disable the new extended_identifier, but it seems like there must be something else wrong. We should be able to query for mounted uploaders.

**Comment by TalLevAmi** [comment]
You can access the extended identifier via ```@book.image.file.identifer``` 
We will look into adding a convenience method for it. 
Note that old records will still have the old format, so you will need to either convert them or search for both formats.

**Comment by adambrod** [comment]
Ok, so you're saying that when I upgrade to carrierwave 1.1, I MUST either
a) migrate the data for every model that uses mount_uploader or else
b) disable the new extended identifier

I just want to be sure I don't break anything when I deploy. Are there any downsides to turning off the extended identifier?

If I want to migrate the data, do you have instructions for where I can get the information to add the extra info to our existing identifiers?

**Comment by TalLevAmi** [comment]
The GEM is backward compatible, the issue is with finding models by their image identifier. If this is a requirement and searching for both cases will not work, then yes, you'll need to migrate your model or disabled the extended identifier.

The extended identifier includes the resource_type and type of the resource to all for easily uploading other resource types. If all you are using is for images of type upload, then disabling the extended identifier is fine. 

If you do want to migrate, you can prepend <resource_type>/<type>/ to identifiers (image/upload/ in most cases). Just make sure you upgrade to the new GEM first.

**Comment by adambrod** [comment]
Oh, ok. I was confused but think I understand now. We aren't using videos or anything at this point so I'll probably just disable.
