### ISSUE TITLE
Edit Examples

### ISSUE THREAD

**Issue by coreyward** [cloudinary/cloudinary_gem#213]
I've not seen any documentation on recommended strategies for handling `#edit` actions with any approach that Cloudinary offers. This information would be very useful in getting started. 
1. For example, how can I tell between a file that has already been processed and one that has not (preloaded image string/id vs already converted to an identifier)?
2. How should I communicate to Cloudinary that an image is no longer in use (or should I even bother)? 
3. What's the best way to handle a `cl_image_upload` where a file already exists, but the user might want to change it? What happens if you're using direct uploads?

Et cetera.

**Comment by taragano** [comment]
Hi @coreyward,

Regarding your questions:

1. I'm not quite sure I fully understand this point, did you mean direct vs indirect-uploads?, or before / after storage?
2. If you're using our CarrierWave integration, then your images are automatically deleted when deleting an associated model record. Otherwise, you can always call the `destroy` API to delete and image from Cloudinary if you need it to be deleted.
3. If your user would like to update an image, and if you'd like the public_id to be kept the same, then you can pass the `public_id` parameter as the `cl_image_upload` options, and then the new upload will overwrite the image on Cloudinary. Note that the old one may still be cached in the CDN, so you may want to include the version component. For more information:
https://support.cloudinary.com/hc/en-us/articles/202520852-How-can-I-update-an-already-uploaded-image-

**Comment by coreyward** [comment]
Using direct uploads. No Carrierwave. 

Your documentation doesn't have any recommendations on how to handle edit actions. Example: when a user edits their profile and submits information. A) if they've specified a new image, what should the controller expect to see? B) If they haven't switched images, how can the controller determine this? 

I was able to ascertain through manual testing that the `cl_image_upload` field ignores an existing value on edit, which means the controller can assume that if an attribute is set for a file field, it needs to be processed.

**Comment by zenspider** [comment]
Where does this stand? It's been ignored for 1.5 years despite the OP answering questions clearly.

@taragano please unassign if you're not going to handle this.

**Comment by taragano** [comment]
@coreyward / @zenspider Sorry for the long delay in my response, it must have fell between the cracks.

It depends whether you parse the [full JSON response](https://cloudinary.com/documentation/upload_images#upload_response) from the upload API, or you get the identifier that's automatically assigned to the field (and then to your controller) by our jQuery library (for example `image/upload/v1517003363/y27mlugrs3itwu6zzjfc.jpg#84ff6e476494175b47fb9f010ecf756dcd5db315`).

If the upload overwrote an existing image, then the JSON response will include the `"overwritten"=>true` value, which lets you know that the old image got overridden by the new uploaded image.
If the customer uploaded the exact same image again, then we'll return `"existing"=>true`.

If the only information you have is the identifier, then you can look at the version value (e.g., `v1517003363`). This value will be different with every new upload, re-uploads (without overwriting) will keep the version value unchanged.

Please let me know if this helps, and whether you have any other questions.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by coreyward** [comment]
No worries, I was able to fix everything by using [Shrine with Imgix](https://github.com/shrinerb/shrine-imgix).
