### ISSUE TITLE
Rails Stale request - reported time is 2016-12-15 04:02:46 +0000 which is more than 1 hour ago

### ISSUE THREAD

**Issue by Hipady** [cloudinary/cloudinary_gem#222]
I get this error every upload using attachinary, I followed every step of the usage and installation. Why am I getting this error?

**Comment by nadavofi** [comment]
This error implies that timestamp provided with the upload payload was outdated (at least by 1 hour). This happens from time to time due to bad timezone or clock configuration on our machine/server. To debug this, you can add some printouts to the code or follow your outgoing upload requests ( browser's network tab or server's logs).

**Comment by nunommc** [comment]
I've encountered exactly the same issue.

I've got two buttons that generate 2 ZIPs:

- `Cloudinary::Utils.download_archive_url(public_ids: photos_after.pluck(:public_id))` this one works fine

- `Cloudinary::Utils.download_archive_url(public_ids: photos_after.pluck(:public_id), transformations: {crop: :scale, width: 1200})` - this one returns the error message above, and I wonder if it's because of the transformations

Are you trying to solve this issue? I reckon it's not related to TMZ issues

**Comment by NotYourAverageDeveloper** [comment]
I haven't been checking github, but I somehow solved this issue a while back.

Possibly from setting the my correct TMZ in application.rb

`config.time_zone = my tmz`

and I've also added [Rack::Synctime](https://github.com/qbart/rack-synctime) gem.

So also `config.middleware.use Rack::Synctime` in application.rb

**Comment by nadavofi** [comment]
@nunommc we may need some more information regarding your use case, as well as pointers to the exact HTTP requests (including your cloud-name) so we can look in our logs and see what went wrong. If privacy is an issue, please feel free to pass this information [via a support ticket](https://support.cloudinary.com/hc/en-us/requests/new).

**Comment by nunommc** [comment]
@nadavofi I'm sorry, I was meant to have deleted my previous comment yesterday as I don't want to confuse more people with this. I no longer have this issue, it was purely because I had accidentally saved the generated URL in record, and it is why it was a stale request.

**Comment by idobarnoam** [comment]
@nunommc 
I'm closing this thread since you are no longer having this issue. 
Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
