### ISSUE TITLE
Isn't there an option to use the uploader widget from Ruby/Rails?

### ISSUE THREAD

**Issue by eloyesp** [cloudinary/cloudinary_gem#230]
I'm adding cloudinary to a Rails application, and the jquery plugin is not what I want, is there any easy way to add the [upload widget](http://cloudinary.com/documentation/upload_widget) to the forms?

I'm using the carrierwave integration and the jquery doesn't seem to have any preview or crop functionality, but may be I'm missing something.

Regards.

**Comment by petertoth** [comment]
Second this. Would highly appreciate if it was possible to require upload widget script in the pipeline.

**Comment by idobarnoam** [comment]
@eloyesp If you are looking for a carrierwave and an upload widget sample project, you could see a good one here: https://github.com/taragano/Carrierwave_widget

@petertoth Currently we don't support requiring the upload widget. We have raised this with our dev team to see if it makes sense to change this and add this support. With that being said, it makes more sense to include the widget only in the upload form page, rather than globally throughout the whole site, as it's is probably be used only on that page (or specific pages)

**Comment by idobarnoam** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
