### ISSUE TITLE
Every version of image i upload creating new url with different version?

### ISSUE THREAD

**Issue by gkmrakesh** [cloudinary/cloudinary_gem#282]
I want constant URL which picks my latest version uploaded of the image.

It is very tedious to change URL of my image every time, can I have constant URL for particular image irrespective of number of uploads for one image.

**Comment by marissa-masangcay** [comment]
Hi, 

The version number component is actually an optional part of the delivery URL that is used to bypass the CDN cached version and force delivery of the newest image. 

Please keep in mind that if you choose to not include the version number in your URLs you want to include the parameter 'invalidate = true' when updating your image so that we will send out an invalidation request to the CDN. This way you won't be displaying the cached image instead of the newly updated image. 

Please feel free to read more about this in our documentation here: https://cloudinary.com/documentation/upload_images#image_versions

**Comment by gkmrakesh** [comment]
Hello @marissa-masangcay 

Thanks for your reply, I am invalidating cache always. Please see below code.

 The problem is even after invalidation, I am not seeing the latest image even after hours.

Please let me know if I am doing anything wrong?

`uploads = {}

# public_id for the uploaded image is generated by Cloudinary's service.
uploads[:pizza] = Cloudinary::Uploader.upload "pizza.jpg",
  :tags => "CodeCoverage",
  :public_id => "Coveragesvg",
  :invalidate => true


puts
puts "* #{uploads.length} images were uploaded and are now available in the cloud."
uploads.each_value.with_index do |upload, index|
  puts "> Upload \##{index+1}:"
  puts "  Public ID: #{upload['public_id']}"
  puts "  URL: #{upload['url']}"
end`

**Comment by marissa-masangcay** [comment]
Hi,

Your code looks great - I do see an invalidation request being processed via your upload call. However, I do see that you have your account configured to invalidate versioned URLs. This means that only URLs with the most recent version are invalidated. And since you don't want to include versions in your URLs I would suggest disabling this configuration or else URLs without the version number won't be invalidated at all.

Something to keep in mind as well is that we treat resources in the root directory different from resources in folders. To view the differences please refer to the invalidation section of our documentation here:

https://cloudinary.com/documentation/upload_images#invalidating_cached_images_on_the_cdn

One last thing I noticed is that you use 'upload[url]' in your code. One thing to note about this is that we always include the version number in response URLs so you may not want to store this particular URL if you don't want the version number included. Below is an example of a static URL that you could use without the version component:

http://res.cloudinary.com/<your_cloud_name>/image/upload/Coveragesvg.jpg

Hope this helps!

**Comment by gkmrakesh** [comment]
Hello @marissa-masangcay

**Thanks for pointing issue,**

**it seems working fine now, though it is taking 5 to 10 minutes to reflect.**

I just have one more question,

Even after I delete images from cloudinary site, i can still retrieve it with URL

Ex: https://res.cloudinary.com/dojc3g7al/image/upload/Coveragesvg.jpg

Is it also caching issue? how can I remove it from cache ?

**Comment by marissa-masangcay** [comment]
Hi,

Deleted images will still be cached on the CDN even after the deletion was processed unless an invalidation request is sent. In order to avoid this you can include the same parameter 'invalidate = true' in the deletion call. Then once the resource has been deleted an invalidation request will be sent to the CDN so you will no longer be able to view the image.

Please note invalidations can take anywhere from a couple of minutes up to an hour.

Hope this helps!

**Comment by gkmrakesh** [comment]
Thank you so much
