### ISSUE TITLE
Unable to use cl_image_tag with CarrierWave

### ISSUE THREAD

**Issue by chaostheory** [cloudinary/cloudinary_gem#307]
I haven't been able to get the cl_image_tag to work with CarrierWave:

`<%= cl_image_tag(item.portrait, secure: true)%>`

`<%= cl_image_tag(item.portrait.full_public_id, secure: true)%>`

`<%= cl_image_tag(item.portrait.common.full_public_id, secure: true)%>`

`<%= cl_image_tag(item.portrait.common, secure: true)%>`

Everything just renders an empty image tag. Is there something I did wrong?

https://support.cloudinary.com/hc/en-us/articles/202520362-Can-Cloudinary-s-imaged-be-served-via-SSL-HTTPS-

https://cloudinary.com/documentation/rails_carrierwave#custom_and_dynamic_transformations

**Comment by taragano** [comment]
The first two lines should have worked successfully indeed.
Have you had the chance of testing out our [sample project](https://github.com/cloudinary/cloudinary_gem/tree/master/samples/photo_album)?
These lines should work well on the sample project, if so, the issue is probably related to a configuration issue, probably in the model or uploader.

Let us know of any updates?

**Comment by chaostheory** [comment]
It could be config. I'll try it with the sample
