### ISSUE TITLE
Invalid URI. URI byte size should not be > 62910000. Given 84720054)

### ISSUE THREAD

**Issue by aruprakshit** [cloudinary/cloudinary_gem#337]
I am using this gem in one of my rails project.

```
# Gemfile
gem 'cloudinary', '~> 1.11', '>= 1.11.1'
gem 'rails', '~> 5.2', '>= 5.2.1'
```

When I try to upload a base64 video, I get error.

```ruby
2.6.2 :005 > Cloudinary::Uploader.upload(File.read(file).strip, :resource_type => :video)
Traceback (most recent call last):
        1: from (irb):5
CloudinaryException (Error in loading data:video/mp4;base64,AAAAGGZ0eXBtcDQyAAAAAGlzb21tc... - Invalid URI. URI byte size should not be > 62910000. Given 84720054)
2.6.2 :006 > Cloudinary::Uploader.upload_large(File.read(file).strip, :resource_type => :video)
Traceback (most recent call last):
        2: from (irb):6
        1: from (irb):6:in `rescue in irb_binding'
CloudinaryException (Error in loading data:video/mp4;base64,AAAAGGZ0eXBtcDQyAAAAAGlzb21tc... - Invalid URI. URI byte size should not be > 62910000. Given 84720054)
2.6.2 :007 > 
```

The file is here https://www.dropbox.com/s/rsindwqqmrvhzuu/video.txt .

**Comment by aleksandar-cloudinary** [comment]
Hi @aruprakshit .

Our current limit on uploading using Base64 Data URI is 60MB which is why you're seeing this error message.

In such cases, we recommend alternate upload options. You can choose from: local path, a remote HTTP or HTTPS URL, a remote S3 URL or an FTP URL. These are described in this specific part of our documentation: https://cloudinary.com/documentation/upload_images#data_upload_options.

**Comment by aruprakshit** [comment]
@aleksandar-cloudinary Oh I see. The data comes from frontend API as base64. I'll see what I can do there.

**Comment by aleksandar-cloudinary** [comment]
Let us know how it goes or if you encounter any issues. You can do this by going to https://support.cloudinary.com or emailing support@cloudinary.com

**Comment by aruprakshit** [comment]
@aleksandar-cloudinary Is there such size restriction when the upload is from any CDN like S3?

**Comment by aleksandar-cloudinary** [comment]
@aruprakshit This specific restriction only applies to the length of the Base64 URIs used as the source of upload.

There are upload restrictions, but these are the standard account level ones in terms of maximum image, video, raw file size. For example, the Free plans have a maximum video upload size of 100MB. These restrictions apply whether you're using S3 or local file upload etc. If you're not on a Free plan or if you would like to see the full account limits for your current plan then you can do this by going to the Settings => Account page: (https://cloudinary.com/console/settings/account) and these will be shown on the right-hand side.

In your case, you can use any public or (whitelisted [1]) private S3 bucket as the source of upload rather than Base64 data URI.

1. https://cloudinary.com/documentation/upload_images#private_storage_url
 https://cloudinary.com/documentation/upload_images#how_to_set_read_access_on_a_private_amazon_s3_bucket
