### ISSUE TITLE
Issue with folders and ActiveStorage

### ISSUE THREAD

**Issue by sdretu** [cloudinary/cloudinary_gem#385]
Hi there

 I am using the Cloudinary GEM version 1.13.2,
using it with ActiveStorage to upload image to a Cloudinary folder, this is the config for Cloudinary in the storage.yml:
```
cloudinary:
  service: Cloudinary
  folder: myfolder
```

This uploads images correctly in the folder, but active storage only stores the latest part of the public_id, without the folder, so the url for the image is not generated properly.

ActiveStorage stores the blobkey as "7l4jwy3hlx1tnx8si4ehahk5vg8b" instead of what I expect would be "myfolder/7l4jwy3hlx1tnx8si4ehahk5vg8b"

This also causes the ActiveStroage worker to fail with ActiveStorage::IntegrityError

Any hint to set up folders?

**Comment by roeeba** [comment]
Hi @Julien-Nicault, thanks for pointing it out. I'm opening a ticket to our engineers and will update once there's any progress done in this matter.

**Comment by TrishaPatel** [comment]
Is there any update on this issue?

**Comment by sedubois** [comment]
Thank you @shirlymanor that would be great. Also, is there a way to specify the folder for when uploading individual ActiveStorage attachments? For instance we might want to store the assets for our different courses in separate folders.

The second part to this question would also be how to move assets which have already been uploaded to Cloudinary. Previously I tried to move them directly in the Cloudinary dashboard, but found out it leads to `ActiveStorage::IntegrityError` as the folder path in Cloudinary conditions the way the asset is being accessed by ActiveStorage. I guess this can be fixed by changing the `ActiveStorage::Blob`'s `key` to contain the folder name as well (although I haven't tried), but would be great to have a way to move assets into different folders while keeping both in sync.
