### ISSUE TITLE
Backuped files key are not consitent on AWS

### ISSUE THREAD

**Issue by ombr** [cloudinary/cloudinary_gem#386]
We are using your product with our own aws s3 backup. We realized the backup keys are not consistent:

image resource type: `res/sadaasdasd/image/authenticated/amazing_id/123123.jpg`
raw resource type: `res/sadaasdasd/image/authenticated/amazing_id.odt/123123`

We had to implement this function, and we think it should be part of this gem:

```
  def self.backup_key(cloudinary)
    prefix = "res/#{Cloudinary.config.cloud_name}/#{cloudinary.resource_type}/#{cloudinary.storage_type}/#{cloudinary.file.public_id}"
    if cloudinary.resource_type == 'raw'
      "#{prefix}.#{cloudinary.format}/#{cloudinary.file.version}"
    else
      "#{prefix}/#{cloudinary.file.version}.#{cloudinary.format}"
    end
  end
```

We only checked raw and image files (authenticated).

There might be more differences on other type or resource_type ? Is this documented somewhere ?

Thanks in advance.

**Comment by aleksandar-cloudinary** [comment]
@ombr raised a ticket with us directly where I replied but also included it here for reference.

The backup folder structure for the keys that Cloudinary uses does indeed differ slightly between Image/Video and Raw resource_types.

This is due to Raw files requiring their extension (aka format) to be as part of the public_id. When uploading Raw files, if you are setting the public_id yourself then you should also include the extension as part of that. Alternatively, if you are relying on Cloudinary to manage the public_id (whether that is using the default random public_id or when specifying the use_filename parameter) then Cloudinary would handle the extension and add it to the public_id automatically.

This also affects the structure of the backup keys for those files. The key structure for Image/Video files is as follows:
`<S3-prefix>/<cloud-name>/<resource_type>/<type>/<public_id>/<version>.<format>`

As noted, the structure for Raw files is slightly different. Because now the format is part of the public_id, it is omitted from the end.
`<S3-prefix>/<cloud-name>/<resource_type>/<type>/<public_id + (format)>/<version>`

We do have a support article on the structure of the backups which can be found here:
https://support.cloudinary.com/hc/en-us/articles/213994945-What-structure-does-Cloudinary-use-to-back-up-my-resources-

While you can copy any of the files from the backup and then process them separately as you require, it's important to note that the structure in the S3 bucket or filenames shouldn't be changed since that will affect the backup process should these files need to be recovered by Cloudinary. In addition, while there aren't any plans to update this structure, in future there may be cases which would require us to modify it depending on the requirements.
