### ISSUE TITLE
Cloudinary::Uploader.upload closes File streams, causing IOError when used in loops

### ISSUE THREAD

**Issue by wam** [cloudinary/cloudinary_gem#90]
We have a rails app that accepts an image file from a form, opens the uploaded Tempfile, and loops over different sets of width and height options, calling `Cloudinary::Uploader.upload` on each loop.

On the 2nd iteration of the loop, we get an `IOError` because the file stream has been closed by RestClient during the API request execution. Since we're in a loop and may be doing other operations on the tempfile, we want the file to stay open until we explicitly close it.

Implicit closure seems to be unavoidable given the dependency on `RestClient::Request`, but perhaps it would be reasonable to open a new stream in `upload` if the file responds to `:read` ([here](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/uploader.rb#L46-48)) and let *that* stream be closed, allowing the user to explicitly handle closing the original stream.

Simplified example:

```ruby
configs = [
  { :crop => :limit, :width => 520, :height => 218 },
  { :crop => :limit, :width => 1040, :height => 436 }
]

uploaded_file.inspect? # <File:/tmp/RackMultipart20131029-4024-1xmzq1s>

configs.each do |options|
  response = Cloudinary::Uploader.upload(uploaded_file, options)
  # do some stuff with response...
  uploaded_file.inspect? # <File:/tmp/RackMultipart20131029-4024-1xmzq1s (closed)>
end
```

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by conor-kelleher** [comment]
Just noting that I just ran into this issue. Different use case but the above solution worked.

We have clients across a bunch of different sub-accounts so we are building a way for admin users to upload assets to all subaccounts (i.e. select a font on their computer and upload it to multiple accounts). This led to the same issue described above with the loop failing since the file is closed on the second iteration.

Copying the file with `File.open(file, "rb")` sorted this for us 👍
